### ISSUE TITLE
IronBank Scripts Integration

### ISSUE THREAD

**Issue by rigzba21** [MetroStar/conda-vendor#36]
We currently maintain several copies of [python scripts that run conda-vendor and generate IronBank formatted files](https://repo1.dso.mil/dsop/opensource/metrostar/singleuser/-/blob/development/scripts/update_ib_files.py) that live in each of our IronBank repo1 git repos. It would be nice to have that functionality integrated as part of conda-vendor's [`iron_bank_generator.py` modle](https://github.com/rigzba21/conda-vendor/blob/34-conda-vendor-improvements/conda_vendor/iron_bank_generator.py). That way we wouldn't have to maintain five or more copies of each of those python scripts, and we could just use the `conda-vendor ironbank-gen` subcommand.

**Comment by rycrow** [comment]
Another consideration is a flag that could be passed in in order to change the output written to stdout to only contain the generated `resources:` block so that the `hardening-manifest`-formatted output of the `vendor` command could be cleanly redirected to a file without any string manipulation.

**Comment by jbouder** [comment]
Closing stale issue
